### ISSUE TITLE
Calling `beforeEach` from implementation code is problematic

### ISSUE THREAD

**Issue by infews** [wagerfield/jasmine-custom-matchers#1]
Great work!

The fact the implementation code calls Jasmine's `beforeEach` is a bit of a surprise. 
- In `boot.js`, developers may rename what's on the global interface and/or may attach to their own reference. So this may break in some situations
- Also, projects have been very vocal about wanting not to install matchers on every spec, which this implementation does, for performance reasons.

I'd recommend breaking out the installation and letting projects do it themselves.

Thanks for contributing to the Jasmine community

**Comment by wagerfield** [comment]
Hi @infews,

Thank you for your rapid feedback :smile:

I've only recently started using Jasmine, so this implementation was something that I found convenient for my projects. Considering how generic these matchers were, I figured they belonged on the global scope alongside Jasmine's existing ones.

However, I am happy to concede to an alternative implementation if you can suggest one?

Originally I added my custom matchers to the same `CustomMatchers` namespace object like so:

``` javascript
var CustomMatchers = CustomMatchers || {};
CustomMatchers.toBeAnInteger = { ... };
```

...and did not wrap this code in an [IIFE](http://en.wikipedia.org/wiki/Immediately-invoked_function_expression). I then added this object within each of my Spec files but felt like I was repeating myself a lot, so added them to the global scope for convenience.

Is what I have done a real sin?

**Comment by infews** [comment]
There is no sin other than not testing. :)

I think adding your matchers to a namespace is a great idea. Your implementation should make them available - maybe by letting developers pass in an object?

Then the key next step is to let projects add them on their own instead of automatically.
